[workspace]
members = [
    "graphics",
    "graphics-macro",
    "engine",
    "engine_examples",
    "vfs",
    "websocket",
]
default-members = [
    "graphics",
    "graphics-macro",
    "engine",
    "engine_examples",
    "vfs",
    "websocket",
]