[workspace]
members = [
    "graphics",
    "engine",
    "engine_examples",
    "vfs",
]
default-members = [
    "graphics",
    "engine",
    "engine_examples",
    "vfs",
]

[patch.crates-io]
wasm-bindgen = { path = "../wasm-bindgen" }
web-sys = { path = "../wasm-bindgen/crates/web-sys" }
js-sys = { path = "../wasm-bindgen/crates/js-sys" }