[package]
name = "solstice-2d"
version = "0.1.0"
authors = ["Tanner Rogalsky <tanner@tannerrogalsky.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solstice = { path = "../solstice", features = ["derive"] }
mint = "0.5"

cgmath = "0.17.0"
lyon_tessellation = "0.15"