[package]
name = "solstice-2d"
version = "0.1.0"
authors = ["Tanner Rogalsky <tanner@tannerrogalsky.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solstice = { version = "0.1", features = ["derive"] }
mint = "0.5"

lyon_tessellation = "0.16"

[dev-dependencies]
glutin = "0.24"
png = "0.16"